package persistance;

// Generated 7 avr. 2013 21:24:23 by Hibernate Tools 3.4.0.CR1

/**
 * Tunisiana generated by hbm2java
 */
public class Tunisiana implements java.io.Serializable {

	private Integer idTunisiana;
	private String login;
	private String type;
	private Float prixActuel;
	private Integer nbreVente;
	private Integer nbreActionRest;

	public Tunisiana() {
	}

	public Tunisiana(String login) {
		this.login = login;
	}

	public Tunisiana(String login, String type, Float prixActuel,
			Integer nbreVente, Integer nbreActionRest) {
		this.login = login;
		this.type = type;
		this.prixActuel = prixActuel;
		this.nbreVente = nbreVente;
		this.nbreActionRest = nbreActionRest;
	}

	public Integer getIdTunisiana() {
		return this.idTunisiana;
	}

	public void setIdTunisiana(Integer idTunisiana) {
		this.idTunisiana = idTunisiana;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Float getPrixActuel() {
		return this.prixActuel;
	}

	public void setPrixActuel(Float prixActuel) {
		this.prixActuel = prixActuel;
	}

	public Integer getNbreVente() {
		return this.nbreVente;
	}

	public void setNbreVente(Integer nbreVente) {
		this.nbreVente = nbreVente;
	}

	public Integer getNbreActionRest() {
		return this.nbreActionRest;
	}

	public void setNbreActionRest(Integer nbreActionRest) {
		this.nbreActionRest = nbreActionRest;
	}

}
