package persistance;

// Generated 7 avr. 2013 21:24:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateurs generated by hbm2java
 */
public class Utilisateurs implements java.io.Serializable {

	private String login;
	private String password;
	private String type;
	private Set<Clients> clientses = new HashSet<Clients>(0);

	public Utilisateurs() {
	}

	public Utilisateurs(String login) {
		this.login = login;
	}

	public Utilisateurs(String login, String password, String type,
			Set<Clients> clientses) {
		this.login = login;
		this.password = password;
		this.type = type;
		this.clientses = clientses;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Clients> getClientses() {
		return this.clientses;
	}

	public void setClientses(Set<Clients> clientses) {
		this.clientses = clientses;
	}

}
